controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

catalogue_delete:
    path: /cataloguedelete/{id}
    controller: App\Controller\CatalogueController::deleteProduct
#[Route("/cataloguedelete/{id}", name:'app_catalogue_delete')]