controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App/Controller/HomeController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_catalogue:
        path: /catalogue
        controller: App\Controller\CatalogueController::displayProducts

app_panier:
    path: /panier
    controller: App\Controller\PanierController::index


